apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-no-dockerfile-ugbq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-no-dockerfile-ugbq
    app.kubernetes.io/part-of: test-app-wdpp
  name: nodejs-no-dockerfile-ugbqlnwh
spec:
  path: /
  port:
    targetPort: 8080
  to:
    kind: Service
    name: nodejs-no-dockerfile-ugbq
    weight: null
status: {}
